cask_args appdir: "/Applications"

tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"

brew "rbenv"
brew "nodebrew"
brew "zsh-completion"
brew "git"
brew "git-secrets"
brew "mas"
brew "tree"
brew "watch"
brew "wget"

cask "docker"
cask "iterm2"
cask "google-chrome"
cask "firefox"
cask "notion"
cask "visual-studio-code"
cask "font-hack-nerd-font"
cask "slack"
